  //
  //  Marvel_HeroesTests-Marvel_HeroesMocks.generated.swift
  //  Marvel_Heroes
  //
  //  Generated by Mockingbird v0.17.0.
  //  DO NOT EDIT
  //

@testable import Marvel_Heroes
@testable import Mockingbird
import Alamofire
import Foundation
import Kingfisher
import Lottie
import Swift
import SwiftHash
import UIKit
private var genericTypesStaticMocks = Mockingbird.Synchronized<[String: Mockingbird.StaticMock]>([:])
